#!/bin/bash

# Run the build script
./build.sh

# Check if the build script was successful
if [ $? -ne 0 ]; then
    echo "Error: Build script failed. Push aborted."
    exit 1
fi

# Add the newly generated PDF and README to the commit
git add docs/python-tech-lead_andres-monge.pdf README.md

# Amend the last commit to include the updated PDF and README
git commit --amend --no-edit

# If everything is successful, allow the push to proceed
exit 0
