* https://beanie-odm.dev/
* FastApi

[tool.poetry.dependencies]
python = ">=3.10,<=3.12"
lmdb = "^1.4.1"
fastapi = "^0.109.0"
uvicorn = "^0.27.0.post1"
python-multipart = "^0.0.6"
faker = "^22.6.0"
aiofiles = "^23.2.1"
python = "^3.11"
watchdog = "^3.0.0"
beautifulsoup4 = "^4.12.2"
rich = "^13.7.0"
ollama = "^0.1.2"
duckduckgo-search = "^4.2"
markdown = "^3.5.2"
openai = "^1.10.0"
langchain = "^0.1.4"
click = "^8.1.7"
twisted = "^23.10.0"
hachiko = "^0.4.0"
service-identity = "^24.1.0"
einops = "^0.7.0"
tiktoken = "^0.6.0"
langchain-community = "^0.0.20"

[tool.poetry.group.dev.dependencies]
https://beanie-odm.dev/
ipdb = "^0.13.13"
flake8 = "^7.0.0"
isort = "^5.13.2"
black = "^24.1.1"
flake8-quotes = "^3.3.2"
pep8-naming = "^0.13.3"
flake8-picky-parentheses = "^0.5.4"
flake8-docstrings = "^1.7.0"
toml = "^0.10.2"
types-toml = "^0.10.8.7"
pyright = "^1.1.349"
bandit = "^1.7.7"
darglint = "^1.8.1"
pylsp-rope = "^0.1.11"
flake8-print = "^5.0.0"
flake8-bandit = "^4.1.1"
flake8-unused-arguments = "^0.0.13"
flake8-comprehensions = "^3.14.0"
flake8-bugbear = "^24.1.17"
flake8-annotations = "^3.0.1"
flake8-black = "^0.3.6"
flake8-docstring-checker = "^1.2"
flake8-eradicate = "^1.5.0"
flake8-builtins = "^2.2.0"
flake8-string-format = "^0.3.0"
flake8-blind-except = "^0.2.1"
flake8-isort = "^6.1.1"
flake8-todo = "^0.7"
autoflake = "^2.2.1"
sourcery-cli = "^1.15.0"
docformatter = "^1.7.5"
ipdb = "^0.13.13"
flake8 = "^6.0.0"
isort = "^5.12.0"
black = "^23.3.0"
flake8-quotes = "^3.3.2"
pep8-naming = "^0.13.3"
flake8-picky-parentheses = "^0.5.0"
flake8-docstrings = "^1.7.0"
toml = "^0.10.2"
types-toml = "^0.10.8.6"
pyright = "^1.1.318"
bandit = "^1.7.5"
hooks4git = "^0.4.289"
darglint = "^1.8.1"
pylsp-rope = "^0.1.11"
flake8-print = "^5.0.0"
flake8-bandit = "^4.1.1"
flake8-unused-arguments = "^0.0.13"
flake8-comprehensions = "^3.14.0"
flake8-bugbear = "^23.7.10"
flake8-annotations = "^3.0.1"
flake8-black = "^0.3.6"
flake8-docstring-checker = "^1.2"
flake8-eradicate = "^1.5.0"
flake8-builtins = "^2.1.0"
flake8-string-format = "^0.3.0"
flake8-blind-except = "^0.2.1"
flake8-isort = "^6.0.0"
flake8-todo = "^0.7"
autoflake = "^2.2.0"
sourcery-cli = "^1.8.0"
debugpy = "^1.6.7.post1"
docformatter = { extras = ["tomli"], version = "^1.7.5" }
