-- Create a command to pick the venv from a file
-- vim.cmd [[
--   function! PickVenvFromFile()
--     " Check if the 'venv.name' file exists in the current directory
--     if filereadable('venv.name')
--       " If it does, read its content to a variable
--       let venv_name = join(readfile('venv.name'), '')
--
--       " Use your module to pick the venv
--       lua require('swenv.api').set_venv(venv_name)
--     endif
--   endfunction
-- ]]

-- Set an autocommand to run the command when a buffer is read
-- vim.cmd [[autocmd BufRead,BufNewFile * :call PickVenvFromFile()]]
