#!/bin/bash

ON(){
  # If argument is 1, load the module
  sudo modprobe uvcvideo
}

OFF(){
  # If argument is 0, unload the module
  sudo kill -9 $(sudo lsof /dev/video0 2>/dev/null | awk 'NR>1 {print $2}') 2> /dev/null
  sudo modprobe -r uvcvideo
}

if [[ $# -eq 0 ]]; then
    # If no arguments were passed, check if the module is loaded
    if lsmod | grep -q 'uvcvideo'; then
      OFF
    else
      ON
    fi
elif [[ $1 -eq 1 ]]; then
  ON
elif [[ $1 -eq 0 ]]; then
  OFF
else
    echo "Invalid argument. Please provide either 1 (to load the module) or 0 \
      (to unload the module), or no arguments to toggle the module."
fi
