#!/bin/bash

get_internal_ip() {
    ip addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '127.0.0.1' | head -n 1
}

get_external_ip() {
    echo "Not implemented error"
    exit 1
}

if [ $# -eq 0 ] || [ "$1" = "internal" ]; then
    get_internal_ip
elif [ "$1" = "external" ]; then
    get_external_ip
else
    echo "Usage: $0 [internal|external]"
    exit 1
fi
