#!/bin/sh

case $(uname -s) in
darwin)
    lsof -i "$1" | grep '(LISTEN)' | awk '{print $2}' | uniq
    ;;
Linux)
    ss -ltnp "sport = :$1" | awk 'NR>1{print $6}' | awk -F '[",=]' '{print $5}' | xargs
    ;;
*)
    echo "Unsupported operating system: $OS"
    ;;
esac
