#!/bin/zsh

echo "sudo pacman -Scc --noconfirm"
sudo pacman -Scc --noconfirm

echo "sudo pacman -Syu --noconfirm"
sudo pacman -Syu --noconfirm

echo "aura -Ayu --noconfirm"
sudo aura -Ayu --noconfirm

echo "sudo snap refresh"
sudo systemctl start snapd.apparmor.service snapd.service
sudo snap refresh
sudo systemctl stop snapd.apparmor.service snapd.service

echo "sudo pacman -Scc --noconfirm"
sudo pacman -Scc --noconfirm

echo "fwupdmgr update -y"
sudo fwupdmgr refresh
sudo fwupdmgr get-updates
sudo fwupdmgr update -y

# echo "User ZSH npm, zinit, ... 'HEADLESS=1 source ~/.zshrc'"
HEADLESS=1 source $HOME/.zshrc

echo "npm update -g"
npm update -G

echo "cargo install-update -a"
cargo install-update -a

echo "zinit self-update && zinit update"
zinit self-update
zinit update --parallel --quiet

echo "neovim update: nvim --headless +'Lazy update | Lazy load coc.nvim | CocUpdateSync | TSUpdate' +qall"
nvim --headless +'Lazy update | Lazy load coc.nvim | CocUpdateSync | TSUpdate' +qall 2>/dev/null
