#!/bin/bash

echo "sudo pacman -Syu --noconfirm"
sudo pacman -Syu --noconfirm

echo "sudo aura -Aua && aura -Ayu --noconfirm"
sudo aura -Aua
sudo aura -Ayu --noconfirm

echo "sudo snap refresh"
sudo snap refresh

echo "fwupdmgr update -y"
sudo fwupdmgr refresh
sudo fwupdmgr get-updates
sudo fwupdmgr update -y

echo "sudo pacman -Scc"
sudo pacman -Scc -y

echo "User ZSH npm, zinit, ... 'source ~/.zshrc'"
source "$HOME/.zshrc"

echo "sudo npm update -g"
sudo npm update

echo "zinit self-update && zinit update"
zinit self-update
zinit update

echo "neovim update: nvim --headless +'Lazy update | Lazy load coc.nvim | CocUpdateSync' +qall"
nvim --headless +'Lazy update | Lazy load coc.nvim | CocUpdateSync' +qall
